# Generated by Django 4.2.23 on 2026-07-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIResult",
            fields=[
                ("exam_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "confirming_doctor_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("has_lesion", models.BooleanField()),
                ("severity_class", models.CharField(max_length=50)),
                ("confidence_score", models.FloatField()),
                ("ai_bbox_data", models.JSONField(blank=True, null=True)),
                (
                    "gradcam_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("heart_score", models.IntegerField(blank=True, null=True)),
                ("mace_risk_percent", models.FloatField(blank=True, null=True)),
                ("doctor_opinion", models.TextField(blank=True, null=True)),
                ("is_confirmed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ai_results",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "doctor_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=128)),
                ("doctor_name", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("hospital_name", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "doctors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Examination",
            fields=[
                ("exam_id", models.IntegerField(primary_key=True, serialize=False)),
                ("patient_id", models.CharField(max_length=50)),
                ("vessel_type", models.CharField(max_length=20)),
                ("video_path", models.CharField(max_length=255)),
                ("key_frame_path", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "examinations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patient_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "primary_doctor_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("kakao_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "social_provider",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("dataset_patient_id", models.CharField(max_length=20)),
                ("patient_name", models.CharField(max_length=20)),
                ("gender", models.CharField(blank=True, max_length=1, null=True)),
                ("age", models.IntegerField()),
                ("history_score", models.IntegerField(blank=True, null=True)),
                ("ecg_result", models.CharField(blank=True, max_length=50, null=True)),
                ("risk_factors_count", models.IntegerField(blank=True, null=True)),
                ("troponin_t_level", models.FloatField(blank=True, null=True)),
                ("underlying_diseases", models.JSONField(blank=True, null=True)),
                ("chief_complaint", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "patients",
                "managed": False,
            },
        ),
    ]
