# Generated by Django 4.2.30 on 2026-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(max_length=20)),
                ('patient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('bbox_data', models.JSONField()),
                ('snapshot_path', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'bookmarks',
                'managed': False,
            },
        ),
    ]
