# Generated by Django 4.2.30 on 2026-07-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_consultation_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMRSignOff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, max_length=50)),
                ('doctor_id', models.CharField(db_index=True, max_length=20)),
                ('finalized', models.BooleanField(default=False)),
                ('final_result', models.TextField(blank=True, default='')),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('emr_transmitted', models.BooleanField(default=False)),
                ('transmitted_at', models.DateTimeField(blank=True, null=True)),
                ('report_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emr_signoffs',
                'ordering': ['-created_at'],
            },
        ),
    ]
