# Generated by Django 4.2.30 on 2026-08-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_emr_signoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAuth",
            fields=[
                ("auth_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=20)),
                ("provider_user_id", models.CharField(max_length=100)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField()),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "patient_auth",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="consultation",
            name="exam_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="memo",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="consultation",
            name="priority",
            field=models.CharField(default="normal", max_length=20),
        ),
        migrations.AddField(
            model_name="consultation",
            name="reference_type",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="requester_id",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
