# Generated by Django 4.2.30 on 2026-08-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_patientauth_consultation_exam_id_consultation_memo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consultation",
            old_name="reference_type",
            new_name="reference_types",
        ),
    ]
