# Generated by Django 4.2.30 on 2026-08-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_chat_memo_consultation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="emrsignoff",
            name="report_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emrsignoff",
            name="report_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
